version: '3.8'

services:
  app:
    image: evaristo00/gfp:0.0.1
    build:
      context: ./gfp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - gfp-network

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: GFP
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gfp-network

volumes:
  db_data:

networks:
  gfp-network:

