package gestion.finanzas.personales.gfp.enums;

public enum ErrorCodes {
    USUARIO_YA_CREADO,USUARIO_NO_ENCONTRADO,PRESUPUESTO_NO_ENCONTRADO, USUARIO_NO_AUTORIZADO, CATEGORIA_NO_ENCONTRADA, VALOR_INVALIDO
}
